const ImageName = {
	Background: 'background',
	Blocks: 'blocks',
	Bushes: 'bushes',
	Coin: 'coin',
	Character: 'character',
	CharacterIdle:'character-idle',
	CharacterRunning:'character-running',
	CharacterJumping:'character-jumping',
	CharacterPunching:'character-punching',
	CharacterHurt:'character-hurt',
	CharacterDeath:'character-death',
	GunIdleShoot:'gunidleandshoot',
	GunRunningAim:'gunrunningaiming',
	GunRunningShoot:'gunrunningshoot',
	Creatures: 'creatures',
	Hearts:'hearts',
	Tiles: 'tiles',
	Map:'map',
	Decoration:'decoration',
	TileMap:'tilemap',
	Toppers: 'toppers',
	Ammo:'ammo',
	WoodCutterWalk:'woodcutterwalk',
	WoodCutterHurt:'woodcutterhurt',
	WoodCutterJump:'woodcutterjump',
	WoodCutterDeath:'woodcutterdeath',
	GraveRobberIdle:'graverobberidle',
	GraveRobberWalk:'graverobberwalk',
	GraveRobberRun:'graverobberrun',
	GraveRobberHurt:'graverobberhurt',
	GraveRobberJump:'graverobberjump',
	GraveRobberDeath:'graverobberdeath',
	Swords:'swords',
	SwordIdle:'swordidle',
	SwordRunning:'swordrunning',
	SwordSwinging:'swordstabbing',
	Chest:'chest',
	Gun:'gun',
	BigPunch:'bigpunch'
};

export default ImageName;
